name: PMB Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

on:
  push:
    branches:
      - main
jobs:
  # https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
  Deploy-Angular-To-Vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: |
          cd pmb-frontend
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          cd pmb-frontend
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          cd pmb-frontend
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  
  Deploy-Springboot-To-Railway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: |
          cd pmb-backend
          railway up --service ppm-backend
